add optional logs

diff --git a/.github/workflows/cloudbuild.yaml b/.github/workflows/cloudbuild.yaml
--- a/.github/workflows/cloudbuild.yaml
+++ b/.github/workflows/cloudbuild.yaml
@@ -1,7 +1,7 @@
 steps:
   - name: 'curlimages/curl'
     id: 'trigger-github-ci'
-    entrypoint: 'sh'
+    entrypoint: 'bash'
     args:
       - -c
       - |
@@ -9,11 +9,18 @@ steps:
 
         echo "Trigger CI for branch ci-cloudbuild-test"
 
-        curl -X POST \
+        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
           -H "Accept: application/vnd.github+json" \
-          -H "Authorization: Bearer $$GITHUB_TOKEN" \
+          -H "Authorization: Bearer $GITHUB_TOKEN" \
           "https://api.github.com/repos/ziuld/fundflow/actions/workflows/ci.yml/dispatches" \
-          -d '{"ref":"ci-cloudbuild-test"}'
+          -d '{"ref":"ci-cloudbuild-test"}')
+
+        echo "GitHub response: $RESPONSE"
+
+        if [ "$RESPONSE" -ne 204 ]; then
+          echo "Error triggering GitHub Actions"
+          exit 1
+        fi
     secretEnv:
       - GITHUB_TOKEN
 
